### PR TITLE
Use JSON and regex source generators, and more properly escape HTML.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
Can you add the `hacktoberfest` label to the PR?

**Comment by pavelsavara** [comment]
@teo-tsirpanis the `IL2026` which was there previously said `Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.` and I didn't realize that `JsonSerializerContext` is the generated stuff. 
Maybe we could improve the IL2026 message to say something about replacing the reflection by code gen via `JsonSerializableAttribute`. That would possibly directed me to `JsonSerializable`'s docs.

What do you think ?

**Comment by teo-tsirpanis** [comment]
Indeed the message does not directly point to the source generator. Nor does the documentation for `JsonTypeInfo<T>` or `JsonSerializerContext`. This can affect discoverability.

**Comment by teo-tsirpanis** [comment]
[Turns out the label should have been named `hacktoberfest-accepted`.](https://hacktoberfest.com/participation/#pr-mr-details)

**Pull request merged**
